// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminPostNewsReducer from "../admin_post_news_reducer";
import AdminRaiseAlertReducer from "../admin_raise_alert_reducer";
import AdminRegisterBotReducer from "../admin_register_bot_reducer";
import AdminResetMarketReducer from "../admin_reset_market_reducer";
import AdminSettleReducer from "../admin_settle_reducer";
import CancelAllReducer from "../cancel_all_reducer";
import CancelOrderReducer from "../cancel_order_reducer";
import JoinReducer from "../join_reducer";
import PlaceOrderReducer from "../place_order_reducer";

export type AdminPostNewsParams = __Infer<typeof AdminPostNewsReducer>;
export type AdminRaiseAlertParams = __Infer<typeof AdminRaiseAlertReducer>;
export type AdminRegisterBotParams = __Infer<typeof AdminRegisterBotReducer>;
export type AdminResetMarketParams = __Infer<typeof AdminResetMarketReducer>;
export type AdminSettleParams = __Infer<typeof AdminSettleReducer>;
export type CancelAllParams = __Infer<typeof CancelAllReducer>;
export type CancelOrderParams = __Infer<typeof CancelOrderReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type PlaceOrderParams = __Infer<typeof PlaceOrderReducer>;

\n