// Generated by packages/bots/src/adaptiveTraining.test.ts. Do not edit by hand; retrain with:
//   PIT_TRAIN=1 pnpm exec vitest run -u packages/bots/src/adaptiveTraining.test.ts
import type { AdaptiveArm, AdaptiveParams, ArmPrior } from './adaptiveTrader';

/** Mean and variance of each arm's 10 s epoch reward (play dollars), measured by playing that arm alone. */
export const ADAPTIVE_PRIORS: Record<AdaptiveArm, ArmPrior> = {
  "make": {
    "mean": -20,
    "variance": 4364
  },
  "momentum": {
    "mean": -6,
    "variance": 585
  },
  "revert": {
    "mean": -2,
    "variance": 2034
  },
  "flat": {
    "mean": 0,
    "variance": 0
  }
};

/** priorWeight and discount chosen on a validation slice of the training paths. */
export const ADAPTIVE_TUNED_PARAMS: Pick<AdaptiveParams, 'reward' | 'priorWeight' | 'discount'> = {"reward":"total","priorWeight":100,"discount":0.97};

export const ADAPTIVE_TRAINING = {
  "realPaths": 133,
  "syntheticSessions": 50,
  "secondsPerSession": 299,
  "epochsPerArm": {
    "make": 5307,
    "momentum": 5307,
    "revert": 5307,
    "flat": 5307
  },
  "data": "BTC-USD, ETH-USD, SOL-USD, LTC-USD 1-minute candles, 2026-09-24T06:31:00.000Z to 2026-10-04T06:31:00.000Z"
};
