import { describe, expect, it } from 'vitest';
// Relative import keeps bots free of a new package dependency; swap for '@the-pit/cop' if the integrator adds it.
import { detectSpoofing, parseEventLog, type CopEvent, type EventLogInput } from '../../cop/src/index';
import { runStream, SPOOFER_OWNER as SPOOFER, STREAM_OWNERS as OWNERS } from './streamSim';

const SEED = 1;
const SECONDS = 60;
const FAST_REQUOTE_MS = 250;

/** Replays rows through the Cop the way the runner does (parseEventLog, then detectSpoofing on a clock). */
function copAlerts(rows: EventLogInput[]) {
  const events = rows.map(parseEventLog).filter((e): e is CopEvent => e !== null);
  const alerts = new Map<string, string>();
  for (let now = 0; now <= SECONDS * 1000 + 30_000; now += FAST_REQUOTE_MS) {
    for (const alert of detectSpoofing(events, now)) alerts.set(alert.evidence.incidentKey, alert.owner);
  }
  return { events, owners: [...alerts.values()] };
}

function mmFills(events: CopEvent[]) {
  return events.filter(e => e.kind === 'trade' && (e.maker === 'mm' || e.taker === 'mm')).length;
}

function rowsTs(name: string, rows: EventLogInput[]) {
  return `export const ${name}: EventLogInput[] = [\n${rows.map(row => `  ${JSON.stringify(row)},`).join('\n')}\n];\n`;
}

describe('Cop fixture streams (packages/cop/fixtures/streams.ts)', () => {
  const streams = {
    mmNoiseInformed: runStream({ seed: SEED, seconds: SECONDS }),
    fastRequoteMm: runStream({ seed: SEED, seconds: SECONDS, mmRequoteMs: FAST_REQUOTE_MS }),
    withSpoofer: runStream({ seed: SEED, seconds: SECONDS, spoofer: true }),
  };

  it('every row parses as a Cop event', () => {
    for (const rows of Object.values(streams)) expect(copAlerts(rows).events).toHaveLength(rows.length);
  });

  it('negative controls: real MM fills and no alerts', () => {
    for (const rows of [streams.mmNoiseInformed, streams.fastRequoteMm]) {
      const { events, owners } = copAlerts(rows);
      expect(mmFills(events)).toBeGreaterThanOrEqual(10);
      expect(owners).toEqual([]);
    }
  });

  it('the fast-requoting MM cancels far more often than the 1 s MM', () => {
    const cancels = (rows: EventLogInput[]) => copAlerts(rows).events.filter(e => e.kind === 'order_cancelled' && e.owner === 'mm').length;
    expect(cancels(streams.fastRequoteMm)).toBeGreaterThan(3 * cancels(streams.mmNoiseInformed));
  });

  it('with the spoofer: alerts fire and every one names the spoofer', () => {
    const { owners } = copAlerts(streams.withSpoofer);
    expect(owners.length).toBeGreaterThanOrEqual(2);
    expect(owners.every(owner => owner === SPOOFER)).toBe(true);
  });

  it('matches the committed fixture (regenerate with: pnpm exec vitest run -u packages/bots)', async () => {
    const file = [
      '// Generated by packages/bots/src/copStreams.test.ts from the real bots and matchOrder. Do not edit by hand;',
      '// regenerate with: pnpm exec vitest run -u packages/bots',
      '// Rows match the Spacetime event_log: payload is JSON.stringify(EngineEvent). Owners are readable names, not identities.',
      "import type { EventLogInput } from '../src/index';",
      '',
      `export const STREAM_SEED = ${SEED};`,
      `export const STREAM_SECONDS = ${SECONDS};`,
      `export const STREAM_OWNERS = ${JSON.stringify(OWNERS)};`,
      `export const SPOOFER_OWNER = ${JSON.stringify(SPOOFER)};`,
      `export const FAST_REQUOTE_MS = ${FAST_REQUOTE_MS};`,
      '',
      '/** 1. MM (requotes every 1 s) + noise-1..3 + informed. Expected alerts: none. */',
      rowsTs('mmNoiseInformed', streams.mmNoiseInformed),
      `/** 2. Same as 1, but the MM cancels and requotes every ${FAST_REQUOTE_MS} ms. Expected alerts: none. */`,
      rowsTs('fastRequoteMm', streams.fastRequoteMm),
      '/** 3. Same as 1, plus the Spoofer (owner SPOOFER_OWNER). Expected alerts: only SPOOFER_OWNER. */',
      rowsTs('withSpoofer', streams.withSpoofer),
    ].join('\n');
    await expect(file).toMatchFileSnapshot('../../cop/fixtures/streams.ts');
  });
});
