import { describe, expect, it } from 'vitest';
// Relative import keeps bots free of a new package dependency; swap for '@the-pit/cop' if the integrator adds it.
import { detectSpoofing, parseEventLog, type CopEvent } from '../../cop/src/index';
import data from '../data/pricePaths.json';
import { ADAPTIVE_PRIORS, ADAPTIVE_TUNED_PARAMS } from './adaptivePriors';
import type { SpooferParams } from './spoofer';
import { ADAPTIVE_OWNER, runSession, SPOOFER_OWNER, STREAM_OWNERS } from './streamSim';

// Real-data tournament and Cop check. Every bot (including the trained adaptive AI) trades on the held-out real price
// paths, with and without the spoofer; the Cop replays each session's event log. Slow, so it runs only on request:
//   PIT_EVAL_REAL=1 pnpm exec vitest run -u packages/bots/src/realDataEval.test.ts
// Writes docs/REAL_DATA_EVAL.md.

const meta = data as { paths: number[][]; stepsPerPath: number; range: { start: string; end: string }; symbols: { symbol: string }[] };
const SECONDS = meta.stepsPerPath - 1;
const heldOut = meta.paths.filter((_, i) => i % 10 >= 7); // the same split the AI never trained on
const OWNERS = [...STREAM_OWNERS, ADAPTIVE_OWNER, SPOOFER_OWNER];

const CONDITIONS: { name: string; spoofer: boolean; spooferParams?: Partial<SpooferParams> }[] = [
  { name: 'No spoofer', spoofer: false },
  { name: 'Spoofer (default: trade 1 s after layering, cancel 1 s after)', spoofer: true },
  { name: 'Evasive spoofer: trades 4 s after layering', spoofer: true, spooferParams: { layerDelayMs: 4_000 } },
  { name: 'Evasive spoofer: cancels 6 s after trading', spoofer: true, spooferParams: { cancelDelayMs: 6_000 } },
];

const breathe = () => new Promise<void>(resolve => setImmediate(resolve)); // keep Vitest's worker RPC responsive
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
const median = (xs: number[]) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)];

/** Owners named by the Cop in one session, one entry per distinct incident (polled every second, like the runner). */
function copAlerts(rows: ReturnType<typeof runSession>['rows']): string[] {
  const events = rows.map(parseEventLog).filter((e): e is CopEvent => e !== null);
  const byIncident = new Map<string, string>();
  for (let now = 0; now <= SECONDS * 1000 + 30_000; now += 1000) {
    for (const alert of detectSpoofing(events, now)) byIncident.set(alert.evidence.incidentKey, alert.owner);
  }
  return [...byIncident.values()];
}

describe.runIf(process.env.PIT_EVAL_REAL)('real-data tournament and Cop check (PIT_EVAL_REAL=1)', () => {
  it('runs every bot and the Cop on the held-out real paths', async () => {
    const pnl: Record<string, Record<string, number[]>> = {};
    const copRows: string[] = [];
    const falseAlarmOwners: Record<string, number> = {};
    for (const condition of CONDITIONS) {
      await breathe();
      let caught = 0;
      let onSpoofer = 0;
      let onOthers = 0;
      let runsWithFalseAlarm = 0;
      let spooferTrades = 0;
      pnl[condition.name] = Object.fromEntries(OWNERS.map(o => [o, []]));
      for (const [i, fundamentalPath] of heldOut.entries()) {
        const result = runSession({ seed: 7_000 + i, seconds: SECONDS, fundamentalPath, adaptive: true,
          adaptiveParams: ADAPTIVE_TUNED_PARAMS, adaptivePriors: ADAPTIVE_PRIORS,
          spoofer: condition.spoofer, spooferParams: condition.spooferParams });
        for (const owner of OWNERS) pnl[condition.name][owner].push(result.pnl[owner]);
        const owners = copAlerts(result.rows);
        const mine = owners.filter(o => o === SPOOFER_OWNER).length;
        onSpoofer += mine;
        onOthers += owners.length - mine;
        if (mine > 0) caught++;
        if (owners.length > mine) runsWithFalseAlarm++;
        for (const o of owners) if (o !== SPOOFER_OWNER) falseAlarmOwners[o] = (falseAlarmOwners[o] ?? 0) + 1;
        spooferTrades += result.rows.filter(r => r.kind === 'trade' && JSON.parse(r.payload).trade.taker === SPOOFER_OWNER).length;
      }
      const caughtCell = condition.spoofer ? `${caught}/${heldOut.length}` : 'n/a';
      copRows.push(`| ${condition.name} | ${heldOut.length} | ${caughtCell} | ${condition.spoofer ? spooferTrades : 'n/a'} | ${onSpoofer} | ${onOthers} | ${runsWithFalseAlarm} |`);
    }

    const leaderboard = (name: string, exclude: string[] = []) => OWNERS.filter(o => !exclude.includes(o))
      .map(o => ({ o, mean: mean(pnl[name][o]), median: median(pnl[name][o]), wins: pnl[name][o].filter(x => x > 0).length }))
      .sort((a, b) => b.mean - a.mean)
      .map((r, rank) => `| ${rank + 1} | ${r.o} | ${Math.round(r.mean)} | ${Math.round(r.median)} | ${r.wins}/${heldOut.length} |`);

    const report = [
      '# Real-data tournament and Cop check',
      '',
      `Generated by \`packages/bots/src/realDataEval.test.ts\`. ${heldOut.length} held-out real price paths ` +
        `(${meta.symbols.map(s => s.symbol).join(', ')} 1-minute candles from Coinbase, ${meta.range.start.slice(0, 10)} to ` +
        `${meta.range.end.slice(0, 10)}, rescaled to HACK ticks; 1 real minute = 1 simulated second), ${SECONDS} s each. ` +
        'These are the paths the adaptive AI never trained on. Every session runs the real matching engine with the market maker, ' +
        'three noise traders, the informed trader (which sees the hidden value) and the trained adaptive AI (which does not); ' +
        'the Cop replays each session\'s event log once a second. Simulated traders, play money: real data shapes only the hidden value.',
      '',
      '## Which model does best (no spoofer)',
      '',
      '| Rank | Bot | Mean profit | Median | Sessions in profit |',
      '|---|---|---|---|---|',
      ...leaderboard('No spoofer', [SPOOFER_OWNER]),
      '',
      '## Same, with the spoofer trading',
      '',
      '| Rank | Bot | Mean profit | Median | Sessions in profit |',
      '|---|---|---|---|---|',
      ...leaderboard(CONDITIONS[1].name),
      '',
      '## How the Cop does on real-data markets',
      '',
      '| Condition | Sessions | Spoofer caught | Spoofer trades | Alerts on spoofer | Alerts on other accounts | Sessions with a false alarm |',
      '|---|---|---|---|---|---|---|',
      ...copRows,
      '',
      Object.keys(falseAlarmOwners).length
        ? `False alarms by account: ${Object.entries(falseAlarmOwners).map(([o, n]) => `${o} ${n}`).join(', ')}.`
        : 'No account other than the spoofer was ever flagged, including the market maker and the adaptive AI.',
      '',
      'Profit is mark-to-market in play dollars per session. "Spoofer trades" counts its opposite-side fills (one per completed ' +
        'cycle, sometimes more). The evasive rows step outside the Cop\'s 3 s / 5 s windows on purpose; see docs/LIMITATIONS.md.',
      '',
    ].join('\n');
    expect(copRows).toHaveLength(CONDITIONS.length);
    await expect(report).toMatchFileSnapshot('../../../docs/REAL_DATA_EVAL.md');
  }, 900_000);
});
