// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  marketId: __t.u32().name("market_id"),
  owner: __t.identity(),
  side: __t.string(),
  price: __t.i32(),
  qty: __t.u32(),
  remaining: __t.u32(),
  status: __t.string(),
  ts: __t.timestamp(),
});
