// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  marketId: __t.u32().name("market_id"),
  price: __t.i32(),
  qty: __t.u32(),
  maker: __t.identity(),
  taker: __t.identity(),
  makerOrderId: __t.u64().name("maker_order_id"),
  takerOrderId: __t.u64().name("taker_order_id"),
  ts: __t.timestamp(),
});
