// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  name: __t.string(),
  cash: __t.i64(),
  isBot: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AdminConfig = __t.object("AdminConfig", {
  ownerIdentity: __t.identity(),
});
export type AdminConfig = __Infer<typeof AdminConfig>;

export const Alert = __t.object("Alert", {
  id: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  score: __t.u32(),
  evidence: __t.string(),
  narration: __t.option(__t.string()),
  ts: __t.timestamp(),
});
export type Alert = __Infer<typeof Alert>;

export const AlertIncident = __t.object("AlertIncident", {
  incidentKey: __t.string(),
});
export type AlertIncident = __Infer<typeof AlertIncident>;

export const BotTickSchedule = __t.object("BotTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type BotTickSchedule = __Infer<typeof BotTickSchedule>;

export const ChainHead = __t.object("ChainHead", {
  id: __t.u32(),
  seq: __t.u64(),
  hash: __t.string(),
});
export type ChainHead = __Infer<typeof ChainHead>;

export const EventChain = __t.object("EventChain", {
  seq: __t.u64(),
  eventId: __t.u64(),
  marker: __t.string(),
  ts: __t.timestamp(),
  prevHash: __t.string(),
  hash: __t.string(),
});
export type EventChain = __Infer<typeof EventChain>;

export const EventLog = __t.object("EventLog", {
  id: __t.u64(),
  kind: __t.string(),
  owner: __t.identity(),
  marketId: __t.u32(),
  payload: __t.string(),
  ts: __t.timestamp(),
});
export type EventLog = __Infer<typeof EventLog>;

export const IdCounter = __t.object("IdCounter", {
  id: __t.u32(),
  nextId: __t.u64(),
});
export type IdCounter = __Infer<typeof IdCounter>;

export const Market = __t.object("Market", {
  id: __t.u32(),
  symbol: __t.string(),
  kind: __t.string(),
  tick: __t.u32(),
  status: __t.string(),
});
export type Market = __Infer<typeof Market>;

export const MarketState = __t.object("MarketState", {
  marketId: __t.u32(),
  lastTradePrice: __t.i32(),
});
export type MarketState = __Infer<typeof MarketState>;

export const News = __t.object("News", {
  id: __t.u64(),
  marketId: __t.u32(),
  text: __t.string(),
  ts: __t.timestamp(),
});
export type News = __Infer<typeof News>;

export const Order = __t.object("Order", {
  id: __t.u64(),
  marketId: __t.u32(),
  owner: __t.identity(),
  side: __t.string(),
  price: __t.i32(),
  qty: __t.u32(),
  remaining: __t.u32(),
  status: __t.string(),
  ts: __t.timestamp(),
});
export type Order = __Infer<typeof Order>;

export const Position = __t.object("Position", {
  id: __t.string(),
  owner: __t.identity(),
  marketId: __t.u32(),
  qty: __t.i32(),
  avgPrice: __t.i32(),
});
export type Position = __Infer<typeof Position>;

export const SimState = __t.object("SimState", {
  id: __t.u32(),
  state: __t.string(),
});
export type SimState = __Infer<typeof SimState>;

export const Trade = __t.object("Trade", {
  id: __t.u64(),
  marketId: __t.u32(),
  price: __t.i32(),
  qty: __t.u32(),
  maker: __t.identity(),
  taker: __t.identity(),
  makerOrderId: __t.u64(),
  takerOrderId: __t.u64(),
  ts: __t.timestamp(),
});
export type Trade = __Infer<typeof Trade>;

